---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
  - "client/src/**/*.js"
  - "client/src/**/*.jsx"

exclude_patterns:
  - "webpack.*.js"
  - "node_modules/"
  - "template/*"
  - "server/test/"
  - "client/src/__tests__/"
  - "server/migrations"
  - "server/models"
  - "e2e/"
