---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- "node_modules/"
- "client/assets/"
- ".nyc_output"
- "coverage"